language: go
env:
  - GO15VENDOREXPERIMENT=1
go:
  - 1.5
  - 1.6
  - 1.7
  - tip
install:
  -
    if ! [[ $(go version) =~ "go version go1.5" ]]; then
      go get -u gopkg.in/alecthomas/gometalinter.v1;
      gometalinter.v1 --install;
    fi
script:
  -
    if ! [[ $(go version) =~ "go version go1.5" ]]; then
      gometalinter.v1 --vendor --disable-all --enable=vet --enable=vetshadow --enable=golint ./...;
    fi
  - go build
